### ISSUE TITLE
CentOS 6 Docker ContainerBuild Failing

### ISSUE THREAD

**Issue by pmorris3** [CentOS/sig-cloud-instance-build#122]
I have been attempting to run the docker containerbuild.sh for centos 6, without much success on a Centos 7.4 host with the latest patches.  Here are the things I have observed.  (Centos 7 builds do work as expected.)
The first error I encountered was this:

```
Running pre-installation scripts
.
Starting package installation process

The installation was stopped due to incomplete spokes detected while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
The exact error message is: 

CmdlineError: Missing package: firewalld.
```

The livemedia-creator command fails.  The first issue seemingly has to do with the presence of line 21 in the kickstart file:

```
firewall --disabled
```

Removing that line allows the process to proceed to post installation before it fails. I am currently guessing this has to do with the use of anaconda on CentOS 7 to parse the Centos 6 kickstart file, given that CentOS 6 doesn't have firewalld.  (It looks like there is a explicit yum remove command for firewalld as well, along with some commands to remove directories for firewalld, which is interesting considering it's not a part of the CentOS 6 distro, I am not sure why this is there.  There is probably a reason.  I haven't seen it in the commit history yet, when I went digging yesterday, but I was interrupted by other issues here.)

The next error set that shows up:

```
Installing rootfiles (158/158)
Performing post-installation setup tasks
Performing post-installation setup tasks
.

Configuring installed system

Running in cmdline mode, no interactive debugging allowed.
The exact error message is: 

[Errno 2] No such file or directory.

The installer will now terminate.
2018-03-08 13:20:59,337: Install failed: novirt_install failed
2018-03-08 13:20:59,338: Removing bad disk image
```
I have yet to have much chance to dig though all the anaconda logs in depth, this is what I found that seems to relate:

```
13:20:46,540 INFO anaconda: Performing post-installation setup tasks
13:20:46,545 INFO anaconda: Performing post-installation setup tasks
13:20:46,545 INFO anaconda: Thread Done: AnaInstallThread (139726017328896)
13:20:46,555 INFO anaconda: Running Thread: AnaConfigurationThread (139726017328896)
13:20:46,555 INFO anaconda: Configuring installed system
13:20:46,670 DEBUG anaconda: running handleException
13:20:46,672 CRIT anaconda: Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run
    threading.Thread.run(self, *args, **kwargs)

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 87, in doConfiguration
    ksdata.services.execute(storage, ksdata, instClass)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 1708, in execute
    iutil.execInSysroot("systemctl", ["enable", svc])

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 315, in execInSysroot
    return execWithRedirect(command, argv, stdin=stdin, root=getSysroot())

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 337, in execWithRedirect
    log_output=log_output, binary_output=binary_output)[0]

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 270, in _run_program
    env_prune=env_prune)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 196, in startProgram
    preexec_fn=preexec, cwd=root, env=env, **kwargs)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

13:20:46,717 DEBUG anaconda: Gtk cannot be initialized
13:20:46,717 DEBUG anaconda: In a non-main thread, sending a message with exception data
13:20:46,717 INFO anaconda: Thread Done: AnaConfigurationThread (139726017328896)
13:20:47,564 DEBUG anaconda: running handleException
13:20:47,565 CRIT anaconda: Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run
    threading.Thread.run(self, *args, **kwargs)

  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 87, in doConfiguration
    ksdata.services.execute(storage, ksdata, instClass)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 1708, in execute
    iutil.execInSysroot("systemctl", ["enable", svc])

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 315, in execInSysroot
    return execWithRedirect(command, argv, stdin=stdin, root=getSysroot())

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 337, in execWithRedirect
    log_output=log_output, binary_output=binary_output)[0]

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 270, in _run_program
    env_prune=env_prune)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 196, in startProgram
    preexec_fn=preexec, cwd=root, env=env, **kwargs)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

13:20:47,566 DEBUG anaconda: Gtk cannot be initialized
13:20:47,566 DEBUG anaconda: In the main thread, running exception
```

This is as far as I made it before deciding to open this issue. I will probably do some more digging as I have time. For me, this isn't working. I don't know if anyone else can confirm similar issues. I've had this on both minimally installed machines and hosts with kitchen sink installs, so I don't think it's due to missing hidden requirements. That said, I could be wrong about that.  Can anyone confirm this is currently working?

**Comment by michaeltaylor-kerauno** [comment]
I ran into this issue as well. I am working on a PR.

**Comment by sashkab** [comment]
Try to `yum install python-six pygtk2`. possibly, you might need `yum install gtk3-devel` as well, not 100% sure yet.

**Comment by sashkab** [comment]
Mine error says something about systemctl now:

```
Configuring installed system

Running in cmdline mode, no interactive debugging allowed.
The exact error message is:

[Errno 2] No such file or directory: 'systemctl'.

The installer will now terminate.
2019-01-29 21:40:22,626: Install failed: novirt_install failed
2019-01-29 21:40:22,631: Removing bad disk image
2019-01-29 21:40:22,632: novirt_install failed
```

Question — how official docker images are building — where can look at infrastructure logs to attempt to fix this problem for myself?

Thanks

**Comment by pmorris3** [comment]
This issue is so old, I don't think it's still relevant.  The way these builds work changes regularly, and we are minor versions of Centos 7 ahead now, along with who knows what changes to the tooling in the relevant SIG.  I am going to close this as I don't think it is relevant any longer.  Someone can open a new issue if they have a similar modern issue. Especially since Centos 6 is EOL in a few months.
