### ISSUE TITLE
this ks file gives me errors. 

### ISSUE THREAD

**Issue by manoflinux** [CentOS/sig-cloud-instance-build#35]
Started a few lines up from where the errors started. 
It starts out fine downloading the rpms and then starts getting bash errors???

.
.
.
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/sqlite-3.3.6-7.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/tar-1.15.1-32.el5_8.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/termcap-5.5-1.20060701.1.noarch.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/tzdata-2014e-1.el5.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/udev-095-14.32.el5.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/util-linux-2.13-0.59.el5_8.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/vim-minimal-7.0.109-7.2.el5.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/yum-3.2.22-40.el5.centos.noarch.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/yum-fastestmirror-1.1.16-21.el5.centos.noarch.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/yum-metadata-parser-1.1.2-4.el5.x86_64.rpm ...OK
Retrieving http://mirror.centos.org/centos/5.11/os/x86_64/CentOS/zlib-1.2.3-7.el5.x86_64.rpm ...OK
warning: libgcc-4.1.2-55.el5.x86_64: Header V3 DSA/SHA1 Signature, key ID e8562897: NOKEY
  Installing: libgcc                       ##################### [  1/112] 
  Installing: setup                        ##################### [  2/112] 
  Installing: filesystem                   ##################### [  3/112] 
error: unpacking of archive failed on file /sys: cpio: chown
  Installing: basesystem                   ##################### [  4/112] 
  Installing: nash                         ##################### [  5/112] 
  Installing: cracklib-dicts               ##################### [  6/112] 
  Installing: termcap                      ##################### [  7/112] 
  Installing: centos-release-notes         ##################### [  8/112] 
  Installing: tzdata                       ##################### [  9/112] 
  Installing: glibc-common                 ##################### [ 10/112] 
  Installing: glibc                        ##################### [ 11/112] 
  Installing: mktemp                       ##################### [ 12/112] 
  Installing: zlib                         ##################### [ 13/112] 
  Installing: chkconfig                    ##################### [ 14/112] 
  Installing: popt                         ##################### [ 15/112] 
  Installing: glib2                        ##################### [ 16/112] 
  Installing: nspr                         ##################### [ 17/112] 
  Installing: bzip2-libs                   ##################### [ 18/112] 
  Installing: audit-libs                   ##################### [ 19/112] 
  Installing: libtermcap                   ##################### [ 20/112] 
  Installing: bash                         ##################### [ 21/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: ncurses                      ##################### [ 22/112] 
  Installing: info                         ##################### [ 23/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: libsepol                     ##################### [ 24/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: readline                     ##################### [ 25/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: sqlite                       ##################### [ 26/112] 
  Installing: nss                          ##################### [ 27/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: sed                          ##################### [ 28/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: elfutils-libelf              ##################### [ 29/112] 
  Installing: expat                        ##################### [ 30/112] 
  Installing: libattr                      ##################### [ 31/112] 
  Installing: libacl                       ##################### [ 32/112] 
  Installing: libstdc++                    ##################### [ 33/112] 
  Installing: db4                          ##################### [ 34/112] 
  Installing: iproute                      ##################### [ 35/112] 
  Installing: pcre                         ##################### [ 36/112] 
  Installing: grep                         ##################### [ 37/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: hmaccalc                     ##################### [ 38/112] 
  Installing: binutils                     ##################### [ 39/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: gawk                         ##################### [ 40/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: cpio                         ##################### [ 41/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: diffutils                    ##################### [ 42/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: less                         ##################### [ 43/112] 
  Installing: gzip                         ##################### [ 44/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: procps                       ##################### [ 45/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: libxml2                      ##################### [ 46/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: iputils                      ##################### [ 47/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: centos-release               ##################### [ 48/112] 
  Installing: crontabs                     ##################### [ 49/112] 
  Installing: redhat-logos                 ##################### [ 50/112] 
  Installing: gdbm                         ##################### [ 51/112] 
  Installing: libsysfs                     ##################### [ 52/112] 
  Installing: sgpio                        ##################### [ 53/112] 
  Installing: cyrus-sasl-lib               ##################### [ 54/112] 
  Installing: libcap                       ##################### [ 55/112] 
  Installing: mingetty                     ##################### [ 56/112] 
  Installing: ethtool                      ##################### [ 57/112] 
  Installing: keyutils-libs                ##################### [ 58/112] 
  Installing: openssl                      ##################### [ 59/112] 
  Installing: python-libs                  ##################### [ 60/112] 
  Installing: python                       ##################### [ 61/112] 
  Installing: cracklib                     ##################### [ 62/112] 
  Installing: iscsi-initiator-utils        ##################### [ 63/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: device-mapper-event          ##################### [ 64/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: dmraid-events                ##################### [ 65/112] 
  Installing: findutils                    ##################### [ 66/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: psmisc                       ##################### [ 67/112] 
  Installing: net-tools                    ##################### [ 68/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: shadow-utils                 ##################### [ 69/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
/usr/sbin/groupadd: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
/usr/sbin/groupadd: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
  Installing: libutempter                  ###                   [ 70/112]warning: group utmp does not exist - using root
  Installing: libutempter                  ##################### [ 70/112] 
  Installing: tar                          ##################### [ 71/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: SysVinit                     ##################### [ 72/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: e2fsprogs-libs               ##################### [ 73/112] 
  Installing: e2fsprogs                    ##################### [ 74/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: lvm2                         ##################### [ 75/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: device-mapper-multipath      ##################### [ 76/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: dmraid                       ##################### [ 77/112] 
  Installing: kpartx                       ##################### [ 78/112] 
  Installing: device-mapper                ##################### [ 79/112] 
  Installing: logrotate                    ##################### [ 80/112] 
  Installing: libselinux                   ##################### [ 81/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: MAKEDEV                      ##################### [ 82/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: coreutils                    ##################### [ 83/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: pam                          ##################### [ 84/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: udev                         ##################### [ 85/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: krb5-libs                    ##################### [ 86/112] 
  Installing: util-linux                   ##################### [ 87/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: mcstrans                     ##################### [ 88/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: rsyslog                      ##################### [ 89/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: initscripts                  ##################### [ 90/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: module-init-tools            ##################### [ 91/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: mkinitrd                     ##################### [ 92/112] 
  Installing: rpm                          ##################### [ 93/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: rpm-libs                     ##################### [ 94/112] 
  Installing: rpm-python                   ##################### [ 95/112] 
  Installing: bind-libs                    ##################### [ 96/112] 
  Installing: python-iniparse              ##################### [ 97/112] 
  Installing: python-elementtree           ##################### [ 98/112] 
  Installing: python-sqlite                ##################### [ 99/112] 
  Installing: m2crypto                     ##################### [100/112] 
  Installing: python-urlgrabber            ##################### [101/112] 
  Installing: yum-metadata-parser          ##################### [102/112] 
  Installing: yum-fastestmirror            ##################### [103/112] 
  Installing: yum                          ##################### [104/112] 
  Installing: openldap                     ##################### [105/112] 
  Installing: libuser                      ##################### [106/112] 
  Installing: passwd                       ##################### [107/112] 
  Installing: bind-utils                   ##################### [108/112] 
  Installing: libselinux-utils             ##################### [109/112] 
  Installing: vim-minimal                  ##################### [110/112] 
  Installing: grub                         ##################### [111/112] 
/bin/sh: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
/bin/sh: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
/bin/sh: error importing function definition for `BASH_FUNC_module'
  Installing: rootfiles                    ##################### [112/112] 
filesystem-2.4.0-3.el5.centos.x86_64 was supposed to be installed but is not!

Traceback (most recent call last):
  File "./ami-creator-master/ami_creator/ami_creator.py", line 222, in <module>
    sys.exit(main())
  File "./ami-creator-master/ami_creator/ami_creator.py", line 204, in main
    creator.configure()
  File "/usr/lib/python2.6/site-packages/imgcreate/creator.py", line 737, in configure
    self._run_post_scripts()
  File "/usr/lib/python2.6/site-packages/imgcreate/creator.py", line 681, in _run_post_scripts
    dir = self._instroot + "/tmp")
  File "/usr/lib64/python2.6/tempfile.py", line 293, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python2.6/tempfile.py", line 228, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/var/tmp/imgcreate-D3rLot/install_root/tmp/ks-script-AflsR5'

**Comment by manoflinux** [comment]
and the centos 6.6 one does this. 
./ami-creator-master/ami_creator/ami_creator.py -c ./centos-6.6.ks -n centos66
mke2fs 1.41.12 (17-May-2010)
Discarding device blocks: done                            
Filesystem label=_/
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
65536 inodes, 262144 blocks
2621 blocks (1.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=268435456
8 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376

Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

This filesystem will be automatically checked every 37 mounts or
180 days, whichever comes first.  Use tune2fs -c or -i to override.
tune2fs 1.41.12 (17-May-2010)
Setting maximal mount count to -1
Setting interval between checks to 0 seconds
/usr/lib/python2.6/site-packages/imgcreate/errors.py:40: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  return str(self.message)
Error creating ami: Unable to download from repo : Cannot retrieve repository metadata (repomd.xml) for repository: CentOS. Please verify its path and try again
umount: /var/tmp/imgcreate-cfkwNF/install_root/var/cache/yum: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
lazy umount succeeded on /var/tmp/imgcreate-cfkwNF/install_root//var/cache/yum

**Comment by jperrin** [comment]
I let this go a bit too long. Apologies. Are you still seeing this issue?
