### ISSUE TITLE
centos-7 ks support for ppc64le platform

### ISSUE THREAD

**Issue by mkumatag** [CentOS/sig-cloud-instance-build#55]
I'm looking for the support of generating the centos docker images for ppc64le platform for which I was exploring this project to create ppc64le ks file to generate the image.

Seems like containerbuild.sh/livemedia-creator media needs the centos boot.iso @ http://mirror.centos.org/altarch/7/os/ppc64le/images/ but I couldn't see any such file like boot.iso file. Can someone tell me how should I really get that iso or is there a alternative to generate the boot.iso and create this image.

**Comment by mkumatag** [comment]
@kbsingh

**Comment by mkumatag** [comment]
@jperrin

**Comment by jperrin** [comment]
The netinstall should work for this as well. http://mirror.centos.org/altarch/7/isos/ppc64le/CentOS-7-AltArch-ppc64le-NetInstall-1511.iso

**Comment by mkumatag** [comment]
I tried the given iso and here are findings:

I faced issue in livemedia-creator to find kernel and initrd because for ppc64le netboot iso fs is bit different than x86. To resolve this issue I patched in the livemedia-creator to fetch it from /ppc/ppc64 instead of /isolinux/.

After this I virt_install is failing with following error:

```
[root@llmtul01b docker]# ./containerbuild.sh centos-7ppc64le.ks 
++ basename ./containerbuild.sh
+ USAGE='USAGE: containerbuild.sh kickstart'
+ KICKSTART=centos-7ppc64le.ks
+ KSNAME=centos-7ppc64le
++ date +%Y%m%d
+ BUILDDATE=20160803
+ BUILDROOT=/var/tmp/containers/20160803/centos-7ppc64le
++ uname -m
+ CONT_ARCH=ppc64le
+ '[' 1 -ne 1 ']'
+ '[' '!' -f /usr/sbin/livemedia-creator ']'
+ '[' -d /var/tmp/containers/20160803/centos-7ppc64le ']'
+ livemedia-creator --logfile=/tmp/centos-7ppc64le-20160803.log --make-tar --ks centos-7ppc64le.ks --image-name=centos-7ppc64le-docker.tar.xz --iso /tmp/boot-7ppc64le.iso
2016-08-03 05:43:21,659: disk_size = 3002MiB
2016-08-03 05:43:21,660: disk_img = /var/tmp/centos-7ppc64le-docker.tar.xz
2016-08-03 05:43:21,660: install_log = /tmp/virt-install.log
mount: /dev/loop1 is write-protected, mounting read-only
2016-08-03 05:43:21,674: Running virt-install.
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (cli:246) Launched with command line: /usr/share/virt-manager/virt-install -n LiveOS-922d0bf8-be8b-4fdc-af0b-2d528e6e521f -r 1024 --noreboot --noautoconsole --debug --graphics none --initrd-inject /root/sig-cloud-instance-build/docker/centos-7ppc64le.ks --disk path=/var/tmp/diskjJxxyA.img,format=raw --disk path=/tmp/boot-7ppc64le.iso,device=cdrom,readonly=on,shareable=on --extra-args ks=file:/centos-7ppc64le.ks inst.cmdline stage2=live:CDLABEL=CentOS_AltArch_7_ppc64le --location /var/tmp/lorax.imgutils.kyG5xy --channel tcp,host=127.0.0.1:33696,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (cli:256) Requesting libvirt URI default
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (cli:260) Received libvirt URI qemu:///system
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (virt-install:354) Requesting virt method 'default', hv type 'default'.
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (virt-install:588) Received virt method 'kvm'
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (virt-install:589) Hypervisor name is 'hvm'
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (virt-install:266) Distilled --network options: ['default']
[Wed, 03 Aug 2016 05:43:21 virt-install 14899] DEBUG (virt-install:182) Distilled --disk options: ['path=/var/tmp/diskjJxxyA.img,format=raw', 'path=/tmp/boot-7ppc64le.iso,device=cdrom,readonly=on,shareable=on']
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (connection:252) Fetching volume XML failed: Storage volume not found: no storage vol with matching path '/var/lib/libvirt/iso/RHEL-LE-7.1-20150219.1-Server-ppc64le-dvd1.iso'
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (distroinstaller:415) DistroInstaller location is a network source.
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:53) Using scratchdir=/var/lib/libvirt/boot
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:407) Finding distro store for location=/var/tmp/lorax.imgutils.kyG5xy
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/.treeinfo
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/content
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/Fedora
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/current/images/MANIFEST
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/daily/MANIFEST
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/.disk/info
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/current/images/MANIFEST
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/install/netboot/version.info
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/SL
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/CentOS
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/VERSION
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/Server
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/Client
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/RedHat
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/images/pxeboot/vmlinuz
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/images/boot.iso
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/boot/boot.iso
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/current/images/netboot/mini.iso
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (urlfetcher:196) local hasFile: Couldn't find /var/tmp/lorax.imgutils.kyG5xy/install/images/boot.iso
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (cli:295)   File "/usr/share/virt-manager/virt-install", line 1081, in <module>
    sys.exit(main())
  File "/usr/share/virt-manager/virt-install", line 1066, in main
    guest = build_guest_instance(conn, options, parsermap)
  File "/usr/share/virt-manager/virt-install", line 626, in build_guest_instance
    options.distro_variant)
  File "/usr/share/virt-manager/virt-install", line 400, in set_install_media
    fail(_("Error validating install location: %s") % str(e))
  File "/usr/share/virt-manager/virtinst/cli.py", line 295, in fail
    logging.debug("".join(traceback.format_stack()))

[Wed, 03 Aug 2016 05:43:22 virt-install 14899] ERROR (cli:296) Error validating install location: Could not find an installable distribution at '/var/tmp/lorax.imgutils.kyG5xy'

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.
[Wed, 03 Aug 2016 05:43:22 virt-install 14899] DEBUG (cli:298) 
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-install", line 393, in set_install_media
    guest.installer.check_location(guest)
  File "/usr/share/virt-manager/virtinst/distroinstaller.py", line 493, in check_location
    ignore = self._get_store(guest, fetcher)
  File "/usr/share/virt-manager/virtinst/distroinstaller.py", line 350, in _get_store
    self._cached_store = urlfetcher.getDistroStore(guest, fetcher)
  File "/usr/share/virt-manager/virtinst/urlfetcher.py", line 462, in getDistroStore
    (fetcher.location, extramsg)))
ValueError: Could not find an installable distribution at '/var/tmp/lorax.imgutils.kyG5xy'

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.
2016-08-03 05:43:22,880: VirtualInstall failed: Problem starting virtual install: Command '['virt-install', '-n', 'LiveOS-922d0bf8-be8b-4fdc-af0b-2d528e6e521f', '-r', '1024', '--noreboot', '--noautoconsole', '--debug', '--graphics', 'none', '--initrd-inject', '/root/sig-cloud-instance-build/docker/centos-7ppc64le.ks', '--disk', 'path=/var/tmp/diskjJxxyA.img,format=raw', '--disk', 'path=/tmp/boot-7ppc64le.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'ks=file:/centos-7ppc64le.ks inst.cmdline stage2=live:CDLABEL=CentOS_AltArch_7_ppc64le', '--location', '/var/tmp/lorax.imgutils.kyG5xy', '--channel', 'tcp,host=127.0.0.1:33696,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']' returned non-zero exit status 1
2016-08-03 05:43:22,880: unmounting the iso
2016-08-03 05:43:22,960: Install failed: Problem starting virtual install: Command '['virt-install', '-n', 'LiveOS-922d0bf8-be8b-4fdc-af0b-2d528e6e521f', '-r', '1024', '--noreboot', '--noautoconsole', '--debug', '--graphics', 'none', '--initrd-inject', '/root/sig-cloud-instance-build/docker/centos-7ppc64le.ks', '--disk', 'path=/var/tmp/diskjJxxyA.img,format=raw', '--disk', 'path=/tmp/boot-7ppc64le.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'ks=file:/centos-7ppc64le.ks inst.cmdline stage2=live:CDLABEL=CentOS_AltArch_7_ppc64le', '--location', '/var/tmp/lorax.imgutils.kyG5xy', '--channel', 'tcp,host=127.0.0.1:33696,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']' returned non-zero exit status 1
2016-08-03 05:43:22,961: ERROR: Image creation failed: Problem starting virtual install: Command '['virt-install', '-n', 'LiveOS-922d0bf8-be8b-4fdc-af0b-2d528e6e521f', '-r', '1024', '--noreboot', '--noautoconsole', '--debug', '--graphics', 'none', '--initrd-inject', '/root/sig-cloud-instance-build/docker/centos-7ppc64le.ks', '--disk', 'path=/var/tmp/diskjJxxyA.img,format=raw', '--disk', 'path=/tmp/boot-7ppc64le.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'ks=file:/centos-7ppc64le.ks inst.cmdline stage2=live:CDLABEL=CentOS_AltArch_7_ppc64le', '--location', '/var/tmp/lorax.imgutils.kyG5xy', '--channel', 'tcp,host=127.0.0.1:33696,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']' returned non-zero exit status 1

real	0m1.525s
user	0m1.257s
sys	0m0.083s
+ mkdir -p /var/tmp/containers/20160803/centos-7ppc64le/docker
+ mv /var/tmp/centos-7ppc64le-docker.tar.xz /var/tmp/containers/20160803/centos-7ppc64le/docker/
mv: cannot stat ‘/var/tmp/centos-7ppc64le-docker.tar.xz’: No such file or directory
+ cat
[root@llmtul01b docker]#

```

Not really sure why virt-install command is failed to find distribution for netboot iso. Above is the output of virt-install command with debug enabled.

This is how iso loopmount looks like:

```
[root@llmtul01b ~]# tree /mnt
/mnt
├── boot
│   └── grub
│       ├── grub.cfg
│       ├── powerpc-ieee1275
│       │   ├── adler32.mod
│       │   ├── affs.mod
│       │   ├── afs.mod
│       │   ├── all_video.mod
│       │   ├── archelp.mod
│       │   ├── bfs.mod
│       │   ├── bitmap.mod
│       │   ├── bitmap_scale.mod
│       │   ├── blocklist.mod
│       │   ├── boot.mod
│       │   ├── btrfs.mod
│       │   ├── bufio.mod
│       │   ├── cat.mod
│       │   ├── cbfs.mod
│       │   ├── cmdline_cat_test.mod
│       │   ├── cmosdump.mod
│       │   ├── cmostest.mod
│       │   ├── cmp.mod
│       │   ├── command.lst
│       │   ├── configfile.mod
│       │   ├── core.elf
│       │   ├── cpio_be.mod
│       │   ├── cpio.mod
│       │   ├── crc64.mod
│       │   ├── cryptodisk.mod
│       │   ├── crypto.lst
│       │   ├── crypto.mod
│       │   ├── datehook.mod
│       │   ├── date.mod
│       │   ├── datetime.mod
│       │   ├── diskfilter.mod
│       │   ├── disk.mod
│       │   ├── div_test.mod
│       │   ├── dm_nv.mod
│       │   ├── echo.mod
│       │   ├── elf.mod
│       │   ├── escc.mod
│       │   ├── eval.mod
│       │   ├── exfat.mod
│       │   ├── exfctest.mod
│       │   ├── ext2.mod
│       │   ├── fat.mod
│       │   ├── file.mod
│       │   ├── font.mod
│       │   ├── fshelp.mod
│       │   ├── fs.lst
│       │   ├── functional_test.mod
│       │   ├── gcry_arcfour.mod
│       │   ├── gcry_blowfish.mod
│       │   ├── gcry_camellia.mod
│       │   ├── gcry_cast5.mod
│       │   ├── gcry_crc.mod
│       │   ├── gcry_des.mod
│       │   ├── gcry_dsa.mod
│       │   ├── gcry_idea.mod
│       │   ├── gcry_md4.mod
│       │   ├── gcry_md5.mod
│       │   ├── gcry_rfc2268.mod
│       │   ├── gcry_rijndael.mod
│       │   ├── gcry_rmd160.mod
│       │   ├── gcry_rsa.mod
│       │   ├── gcry_seed.mod
│       │   ├── gcry_serpent.mod
│       │   ├── gcry_sha1.mod
│       │   ├── gcry_sha256.mod
│       │   ├── gcry_sha512.mod
│       │   ├── gcry_tiger.mod
│       │   ├── gcry_twofish.mod
│       │   ├── gcry_whirlpool.mod
│       │   ├── geli.mod
│       │   ├── gettext.mod
│       │   ├── gfxmenu.mod
│       │   ├── gfxterm_background.mod
│       │   ├── gfxterm_menu.mod
│       │   ├── gfxterm.mod
│       │   ├── gptsync.mod
│       │   ├── gzio.mod
│       │   ├── halt.mod
│       │   ├── hashsum.mod
│       │   ├── hello.mod
│       │   ├── help.mod
│       │   ├── hexdump.mod
│       │   ├── hfs.mod
│       │   ├── hfspluscomp.mod
│       │   ├── hfsplus.mod
│       │   ├── http.mod
│       │   ├── ieee1275_fb.mod
│       │   ├── iso9660.mod
│       │   ├── jfs.mod
│       │   ├── jpeg.mod
│       │   ├── keystatus.mod
│       │   ├── ldm.mod
│       │   ├── linux.mod
│       │   ├── loadenv.mod
│       │   ├── loopback.mod
│       │   ├── lsmmap.mod
│       │   ├── ls.mod
│       │   ├── luks.mod
│       │   ├── lvm.mod
│       │   ├── lzopio.mod
│       │   ├── macbless.mod
│       │   ├── macho.mod
│       │   ├── mdraid09_be.mod
│       │   ├── mdraid09.mod
│       │   ├── mdraid1x.mod
│       │   ├── memdisk.mod
│       │   ├── memrw.mod
│       │   ├── minicmd.mod
│       │   ├── minix2_be.mod
│       │   ├── minix2.mod
│       │   ├── minix3_be.mod
│       │   ├── minix3.mod
│       │   ├── minix_be.mod
│       │   ├── minix.mod
│       │   ├── moddep.lst
│       │   ├── mpi.mod
│       │   ├── msdospart.mod
│       │   ├── net.mod
│       │   ├── newc.mod
│       │   ├── nilfs2.mod
│       │   ├── normal.mod
│       │   ├── ntfscomp.mod
│       │   ├── ntfs.mod
│       │   ├── odc.mod
│       │   ├── offsetio.mod
│       │   ├── ofnet.mod
│       │   ├── part_acorn.mod
│       │   ├── part_amiga.mod
│       │   ├── part_apple.mod
│       │   ├── part_bsd.mod
│       │   ├── part_dfly.mod
│       │   ├── part_dvh.mod
│       │   ├── part_gpt.mod
│       │   ├── partmap.lst
│       │   ├── part_msdos.mod
│       │   ├── part_plan.mod
│       │   ├── part_sun.mod
│       │   ├── part_sunpc.mod
│       │   ├── parttool.lst
│       │   ├── parttool.mod
│       │   ├── password.mod
│       │   ├── password_pbkdf2.mod
│       │   ├── pbkdf2.mod
│       │   ├── pbkdf2_test.mod
│       │   ├── png.mod
│       │   ├── priority_queue.mod
│       │   ├── probe.mod
│       │   ├── procfs.mod
│       │   ├── progress.mod
│       │   ├── raid5rec.mod
│       │   ├── raid6rec.mod
│       │   ├── read.mod
│       │   ├── reboot.mod
│       │   ├── regexp.mod
│       │   ├── reiserfs.mod
│       │   ├── relocator.mod
│       │   ├── romfs.mod
│       │   ├── scsi.mod
│       │   ├── search_fs_file.mod
│       │   ├── search_fs_uuid.mod
│       │   ├── search_label.mod
│       │   ├── search.mod
│       │   ├── serial.mod
│       │   ├── setjmp.mod
│       │   ├── setjmp_test.mod
│       │   ├── sfs.mod
│       │   ├── signature_test.mod
│       │   ├── sleep.mod
│       │   ├── sleep_test.mod
│       │   ├── squash4.mod
│       │   ├── suspend.mod
│       │   ├── syslinuxcfg.mod
│       │   ├── tar.mod
│       │   ├── terminal.lst
│       │   ├── terminal.mod
│       │   ├── test_blockarg.mod
│       │   ├── testload.mod
│       │   ├── test.mod
│       │   ├── testspeed.mod
│       │   ├── tftp.mod
│       │   ├── tga.mod
│       │   ├── time.mod
│       │   ├── TRANS.TBL
│       │   ├── trig.mod
│       │   ├── tr.mod
│       │   ├── true.mod
│       │   ├── udf.mod
│       │   ├── ufs1_be.mod
│       │   ├── ufs1.mod
│       │   ├── ufs2.mod
│       │   ├── verify.mod
│       │   ├── video_colors.mod
│       │   ├── video_fb.mod
│       │   ├── videoinfo.mod
│       │   ├── video.lst
│       │   ├── video.mod
│       │   ├── videotest_checksum.mod
│       │   ├── videotest.mod
│       │   ├── xfs.mod
│       │   ├── xnu_uuid.mod
│       │   ├── xnu_uuid_test.mod
│       │   ├── xzio.mod
│       │   ├── zfscrypt.mod
│       │   ├── zfsinfo.mod
│       │   └── zfs.mod
│       └── TRANS.TBL
├── images
│   └── netboot
│       ├── ppc64.img
│       └── TRANS.TBL
├── LiveOS
│   ├── squashfs.img
│   └── TRANS.TBL
└── ppc
    ├── bootinfo.txt
    ├── magic
    ├── mapping
    ├── ppc64
    │   ├── initrd.img
    │   ├── TRANS.TBL
    │   └── vmlinuz
    └── TRANS.TBL
```

**Comment by mkumatag** [comment]
To get around above issue, I was about to patch the code into virt_install /usr/share/virt-manager/virtinst/urlfetcher.py file to look for the kernel and initrd in pcc/pcc64 folder.

By looking into these sort of issues, IMO will have to see whether we can change the FS layout as x86 iso or we might need chase whole world to look for kernel and initrd files in different folder for ppc64le system type.

**Comment by mkumatag** [comment]
After the patch to the livemedia-creator and virt-install, I'm able to proceed further and hit a issue with automatic installation with kickstart. Installation failed with error : "Installation Destination."

https://stackoverflow.com/questions/38782896/centos-automatic-installation-fails-with-installation-destination-error

Can someone help me here to get rid of this error?

**Comment by mkumatag** [comment]
@kbsingh

**Comment by mkumatag** [comment]
There was a missing partition needed in the kickstart file for ppc64le platform, with that script is running fine.

**Comment by kbsingh** [comment]
Please post the changed file needed, so its useful for other people as well

**Comment by mkumatag** [comment]
I would love to do that but I can't until and unless I get official approval from my company. To get approval I need a licence information of this project which is currently missing, created issue https://github.com/CentOS/sig-cloud-instance-build/issues/57 to track the same. I'll propose the changes as soon as I get this licence information incorporated.
